#include <bits/stdc++.h>
#define ll long long
#define vi vector<int>
#define pii pair<int,int>
#define vii vector<pii>
#define rep(i , a , b) for(int i=a ; i<b ; i++)
#define ff first
#define ss second
#define setBits(x) builtin_popcount(x)
using namespace std;
int main()
{
    #ifndef ONLINE_JUDGE
        freopen("input.txt", "r", stdin);
        freopen("output.txt", "w", stdout);
        freopen("error.txt", "w", stderr);
    #endif

    int no_of_classroom ;
    int labs ;
    int semester ;
    int division ;
    cin >>no_of_classroom>>labs>>semester>>division ;

    // ### Faculty input 

    int no_of_faculty ; cin>>no_of_faculty;
    
    for(int faculty = 0 ; faculty<no_of_faculty ; faculty++){
        
    }
    
    return 0;
}